# Generated by Django 3.1 on 2020-08-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee', models.IntegerField()),
                ('operation', models.IntegerField()),
                ('count', models.FloatField()),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('f', models.CharField(max_length=255)),
                ('i', models.CharField(max_length=255)),
                ('o', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_begin', models.TimeField()),
                ('time_finish', models.TimeField()),
                ('descript', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('mensure', models.IntegerField()),
                ('count', models.FloatField()),
                ('price', models.FloatField()),
                ('task', models.IntegerField()),
                ('employee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.IntegerField()),
                ('operation', models.IntegerField()),
                ('count', models.FloatField()),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.IntegerField()),
                ('task', models.IntegerField()),
                ('is_take', models.BooleanField(null=True)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descript', models.CharField(max_length=255)),
                ('task_section', models.IntegerField()),
                ('date', models.DateField()),
                ('time_begin', models.TimeField()),
                ('time_finish', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task_section',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descript', models.CharField(max_length=255)),
                ('object', models.IntegerField()),
            ],
        ),
    ]
