# Generated by Django 3.1 on 2020-09-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measure',
            new_name='Mens',
        ),
        migrations.RenameField(
            model_name='accept',
            old_name='employee',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='adress',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='employee',
            new_name='mens',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='descript',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='mensure',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='time_begin',
            new_name='time1',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='time_finish',
            new_name='time2',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='is_take',
            new_name='take',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_begin',
            new_name='time1',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_finish',
            new_name='time2',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='task',
        ),
        migrations.AddField(
            model_name='accept',
            name='salary',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='salary',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
