# Generated by Django 3.1 on 2020-09-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0002_auto_20200908_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='adress',
            new_name='adres',
        ),
    ]
