# Generated by Django 3.1 on 2020-09-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0004_pass_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='salary',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
