# Generated by Django 3.1 on 2020-09-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokoro', '0005_pass_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='employee',
        ),
    ]
